{{- if or .Values.forecaster.tls.certManager.enabled .Values.scaler.tls.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kedastral.fullname" . }}-selfsigned
  labels:
    {{- include "kedastral.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kedastral.fullname" . }}-ca
  labels:
    {{- include "kedastral.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kedastral.fullname" . }}-ca
  duration: 87600h  # 10 years
  isCA: true
  commonName: kedastral-ca
  subject:
    organizations:
      - kedastral
  issuerRef:
    name: {{ include "kedastral.fullname" . }}-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kedastral.fullname" . }}-ca-issuer
  labels:
    {{- include "kedastral.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "kedastral.fullname" . }}-ca
{{- end }}
